import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import { useForm } from 'react-hook-form'
import { useState } from 'react'
import Router from 'next/router'

const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Home () {

  const { data, error } = useSWR('/api/fetchComments', fetcher)

  const {
    handleSubmit,
    register,
    formState: { errors }
  } = useForm()

  const onSubmit = handleSubmit(async formData => {

    try {
      const res = await fetch('/api/createNewComment', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(formData)
      })
      // if (res.status === 200) {
      //   Router.push('/')
      // } else {
      //   throw new Error(await res.text())
      // }
    } catch (error) {
      console.error(error)
      setErrorMessage(error.message)
    }
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.thread}>
          <div>
            {data?.map((d, index) => {
              return <div key={index}>{d.data.comment}</div>
            })}
          </div>
        </div>

        <form onSubmit={onSubmit}>
          <div>
            <label>Comment</label>
            <input
              type='text'
              placeholder='comment'
              {...register('comment', { required: 'Comment is required' })}
            />
            {errors.lastName && (
              <span role='alert' className='error'>
                {errors.lastName.message}
              </span>
            )}
          </div>

          <div className='submit'>
            <button type='submit' className='submitButton'>
              Create
            </button>
          </div>
        </form>

        {/* <form onSubmit={onSubmit}>
          TODO: Create a new comment
          <textarea></textarea>
          <button>Submit a new comment</button>
        </form> */}
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  )
}
